### ISSUE TITLE
Feature Request: Separate CP invested and Worker Fulfilled

### ISSUE THREAD

**Issue by HavocsCall** [shrddr/workermanjs#6]
I recently came across your site and find it fantastic. However, I am relatively new to the game and just now setting up the worker empire. I am investing CP into nodes, but I don't always have the energy to hire a worker yet. 

I am asking if you could add a way to track if the node is invested, but no worker is assigned yet. So maybe add a button to the node menu to invest CP and keep the "Hire+Assign" worker button as is?

**Comment by shrddr** [comment]
your situation is temporary so let me suggest you use personal notes to keep track of this. i'd rather keep the focus of the project on worker management and not disperse the effort into map management etc
